### ISSUE TITLE
Jenkins agent on Linux / Docker throws error when reconnecting after controller restart

### ISSUE THREAD

**Issue by Kalmalyzer** [falldamagestudio/UE-Jenkins-Images#5]
When the controller goes down, agents' WebSocket connections are terminated. They will then move over to querying the /login API, and wait for that to return a 200 response code. So far so good.

However, once the controller is available again, the agent throws an unhandled exception:

```
May 11, 2021 8:46:03 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Terminated
May 11, 2021 8:46:03 AM hudson.remoting.jnlp.Main$CuiListener status

[Unit]
INFO: Read side closed
May 11, 2021 8:46:03 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Read side closed
May 11, 2021 8:46:03 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: http://10.132.15.250/login is not ready: 503
May 11, 2021 8:46:13 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: http://10.132.15.250/login is not ready: 503
May 11, 2021 8:46:23 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: http://10.132.15.250/login is not ready: 503
May 11, 2021 8:46:33 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: http://10.132.15.250/login is not ready: 503
May 11, 2021 8:46:43 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: http://10.132.15.250/login is not ready: 503
May 11, 2021 8:46:53 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: http://10.132.15.250/login is not ready: 503
May 11, 2021 8:47:03 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: http://10.132.15.250/login is not ready: 503
May 11, 2021 8:47:13 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: http://10.132.15.250/login is not ready: 503
May 11, 2021 8:47:23 AM hudson.remoting.Engine lambda$new$0
SEVERE: Uncaught exception in Engine thread Thread[Thread-0,5,main]
java.lang.NoClassDefFoundError: jenkins/slaves/restarter/JnlpSlaveRestarterInstaller
        at jenkins.slaves.restarter.JnlpSlaveRestarterInstaller$FindEffectiveRestarters$1.onReconnect(JnlpSlaveRestarterInstaller.java:92)
        at hudson.remoting.EngineListenerSplitter.onReconnect(EngineListenerSplitter.java:54)
        at hudson.remoting.Engine.runWebSocket(Engine.java:652)
        at hudson.remoting.Engine.run(Engine.java:470)
Caused by: java.lang.ClassNotFoundException: jenkins.slaves.restarter.JnlpSlaveRestarterInstaller
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at hudson.remoting.RemoteClassLoader.findClass(RemoteClassLoader.java:215)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 4 more
```

This exception is thrown when the agent runs its reconnect flow, [starting here](https://github.com/jenkinsci/remoting/blob/f767654728b076666aea35520fffc651e342ed43/src/main/java/hudson/remoting/Engine.java#L658) and the specific exception is thrown [here](https://github.com/jenkinsci/jenkins/blob/3b1e551235f8d5c6e61f07be688402f9416de5b4/core/src/main/java/jenkins/slaves/restarter/JnlpSlaveRestarterInstaller.java#L92). It seems that the `r` variable is pointing to a type that is no longer known to the agent JVM after the remoting channel has been broken?

The agent has been changed to exit with failure (and wait a few seconds, then re-launching the agent service) when this happens, but, it would be a lot better if the agent would reconnect gracefully within the same agent process. The fail-and-restart behaviour is reasonable when the agents are idle, but not if the agents are currently processing jobs.

**Comment by Kalmalyzer** [comment]
The Docker (non-Kubernetes) agents. This one is no longer relevant. Won't fix.
